---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hse-coursework-health
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'auth-api'
        metrics_path: /auth-api/metrics
        static_configs:
          - targets: ['hse-coursework-health.ru']

      - job_name: 'data-collection-api'
        metrics_path: /data-collection-api/metrics
        static_configs:
          - targets: ['hse-coursework-health.ru']

      - job_name: 'notifications-api'
        metrics_path: /notifications-api/metrics
        static_configs:
          - targets: ['hse-coursework-health.ru']

      - job_name: 'ratings-api'
        metrics_path: /ratings-api/metrics
        static_configs:
          - targets: ['hse-coursework-health.ru']

      - job_name: 'test-app'
        metrics_path: /test-app/metrics
        static_configs:
          - targets: ['hse-coursework-health.ru']

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: hse-coursework-health
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: hse-coursework-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.route-prefix=/prometheus"
            - "--web.external-url=/prometheus"
          ports:
            - containerPort: 9090
              name: web
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: hse-coursework-health
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: web
      protocol: TCP
      name: web
